global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "ticketplaza_prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
    metrics_path: "/metrics"

  - job_name: "ticketplaza_springboot"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:1122" ]
    metrics_path: "/actuator/prometheus"

  - job_name: "ticketplaza_node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9100" ]

  - job_name: "ticketplaza_mysqld-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9104" ]
    metrics_path: "/metrics"

  - job_name: "ticketplaza_redis-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "host.docker.internal:9121" ]
    metrics_path: "/metrics"
