version: "3.8"

services:
  #  ticketplaza_springboot:
  #    image: ticketplaza_springboot_image
  #    container_name: ticketplaza_springboot
  #    ports:
  #      - "1122:1122"
  #    networks:
  #      - ticketplaza_network

  prometheus:
    image: prom/prometheus:latest
    container_name: ticketplaza_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - ticketplaza_network

  grafana:
    image: grafana/grafana
    container_name: ticketplaza_grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SING_UP=false
      - GF_SERVER_DOMAIN=localhost
      # enable logger
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alermanager:debug ngalert:debug
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - "3090:3000"
    networks:
      - ticketplaza_network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: ticketplaza_node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/roofs:ro
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    ports:
      - "9100:9100"
    networks:
      - ticketplaza_network

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: ticketplaza_mysqld_exporter
    ports:
      - "9104:9104"
    command:
      - '--collect.engine_innodb_status'
      - '--collect.info_schema.processlist'
      - '--collect.info_schema.tables'
      - '--collect.info_schema.query_response_time'
      - '--collect.perf_schema.file_events'
      - '--collect.perf_schema.eventsstatements'
      - '--collect.perf_schema.indexiowaits'
      - '--collect.global_status'
      - '--config.my-cnf=/etc/mysql/.my.cnf'
    volumes:
      - ./mysqld-exporter/.my.cnf:/etc/mysql/.my.cnf
    environment:
      - DATA_SOURCE_NAME=root:root@tcp(mysql:3306)/
    networks:
      - ticketplaza_network

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: ticketplaza_redis_exporter
    command: -redis.addr redis://host.docker.internal:6379
    ports:
      - "9121:9121"
    networks:
      - ticketplaza_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: ticketplaza_elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elk/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - ticketplaza_network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.2
    container_name: ticketplaza_logstash
    volumes:
      - ./elk/logstash.yaml:/usr/share/logstash/config/logstash.yml
      - ./elk/pipeline:/usr/share/logstash/pipeline
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "5033:5000/tcp"
      - "5022:5000/udp"
      - "9600:9600"
    networks:
      - ticketplaza_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: ticketplaza_kibana
    volumes:
      - ./elk/kibana.yaml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - ticketplaza_network

networks:
  ticketplaza_network:
    driver: bridge
